language: go

go:
  - "1.19"

env:
  global:
    - GO111MODULE=on
    - GOPRIVATE=github.com/futurehomeno

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls

script:
  - cd ./src && golangci-lint run ./... --timeout 2m && cd ..
  - cd ./src && go test -v -coverpkg=./... -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-pro -repotoken 9tYyQ41UXrd1aSCVntzB3rDgjUJcARs3E