language: go

go:
  - "1.17"

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1

script:
  - cd src && golangci-lint run ./... --timeout 2m && cd ..
  - cd src && go test -p 1 -v ./...
