language: go

go:
  - "1.20"

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - GOPRIVATE=github.com/futurehomeno

install:
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - go install golang.org/x/tools/cmd/cover@latest
  - go install github.com/mattn/goveralls@latest

script:
  - cd ./src && golangci-lint run ./... --timeout 2m && cd ..
  - docker run -d -p 11883:1883 --restart=always eclipse-mosquitto:1.6.8
  - cd ./src && go test -v -count 1 -coverpkg=./... -covermode=count -coverprofile=profile_full.cov ./...
  - cat profile_full.cov | grep -v mock | grep -v test > profile.cov;
  - goveralls -coverprofile=profile.cov -service=travis-pro -repotoken 9tYyQ41UXrd1aSCVntzB3rDgjUJcARs3E