// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedcache

import (
	time "time"

	chargepoint "github.com/futurehomeno/cliffhanger/adapter/service/chargepoint"
	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// CableAlwaysLocked provides a mock function with no fields
func (_m *Cache) CableAlwaysLocked() (bool, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CableAlwaysLocked")
	}

	var r0 bool
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (bool, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// CableCurrent provides a mock function with no fields
func (_m *Cache) CableCurrent() (*int64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CableCurrent")
	}

	var r0 *int64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (*int64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// CableLocked provides a mock function with no fields
func (_m *Cache) CableLocked() (bool, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CableLocked")
	}

	var r0 bool
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (bool, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// ChargerState provides a mock function with no fields
func (_m *Cache) ChargerState() (chargepoint.State, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargerState")
	}

	var r0 chargepoint.State
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (chargepoint.State, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chargepoint.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(chargepoint.State)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// EnergySession provides a mock function with no fields
func (_m *Cache) EnergySession() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnergySession")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// GridType provides a mock function with no fields
func (_m *Cache) GridType() (chargepoint.GridType, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GridType")
	}

	var r0 chargepoint.GridType
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (chargepoint.GridType, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chargepoint.GridType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(chargepoint.GridType)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// LifetimeEnergy provides a mock function with no fields
func (_m *Cache) LifetimeEnergy() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LifetimeEnergy")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// MaxCurrent provides a mock function with no fields
func (_m *Cache) MaxCurrent() (int64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxCurrent")
	}

	var r0 int64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (int64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// OfferedCurrent provides a mock function with no fields
func (_m *Cache) OfferedCurrent() (int64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OfferedCurrent")
	}

	var r0 int64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (int64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// OutputPhaseType provides a mock function with no fields
func (_m *Cache) OutputPhaseType() (chargepoint.PhaseMode, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutputPhaseType")
	}

	var r0 chargepoint.PhaseMode
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (chargepoint.PhaseMode, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chargepoint.PhaseMode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(chargepoint.PhaseMode)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// Phase1Current provides a mock function with no fields
func (_m *Cache) Phase1Current() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Phase1Current")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// Phase2Current provides a mock function with no fields
func (_m *Cache) Phase2Current() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Phase2Current")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// Phase3Current provides a mock function with no fields
func (_m *Cache) Phase3Current() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Phase3Current")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// PhaseMode provides a mock function with no fields
func (_m *Cache) PhaseMode() (int, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PhaseMode")
	}

	var r0 int
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (int, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// Phases provides a mock function with no fields
func (_m *Cache) Phases() (int, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Phases")
	}

	var r0 int
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (int, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// RequestedOfferedCurrent provides a mock function with no fields
func (_m *Cache) RequestedOfferedCurrent() (int64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestedOfferedCurrent")
	}

	var r0 int64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (int64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// SetCableAlwaysLocked provides a mock function with given fields: alwaysLocked, timestamp
func (_m *Cache) SetCableAlwaysLocked(alwaysLocked bool, timestamp time.Time) bool {
	ret := _m.Called(alwaysLocked, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetCableAlwaysLocked")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(bool, time.Time) bool); ok {
		r0 = rf(alwaysLocked, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetCableCurrent provides a mock function with given fields: current, timestamp
func (_m *Cache) SetCableCurrent(current *int64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetCableCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*int64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetCableLocked provides a mock function with given fields: locked, timestamp
func (_m *Cache) SetCableLocked(locked bool, timestamp time.Time) bool {
	ret := _m.Called(locked, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetCableLocked")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(bool, time.Time) bool); ok {
		r0 = rf(locked, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetChargerState provides a mock function with given fields: state, timestamp
func (_m *Cache) SetChargerState(state chargepoint.State, timestamp time.Time) bool {
	ret := _m.Called(state, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetChargerState")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(chargepoint.State, time.Time) bool); ok {
		r0 = rf(state, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetEnergySession provides a mock function with given fields: energy, timestamp
func (_m *Cache) SetEnergySession(energy float64, timestamp time.Time) bool {
	ret := _m.Called(energy, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetEnergySession")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(energy, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetInstallationParameters provides a mock function with given fields: gridType, phases, timestamp
func (_m *Cache) SetInstallationParameters(gridType chargepoint.GridType, phases int, timestamp time.Time) bool {
	ret := _m.Called(gridType, phases, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetInstallationParameters")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(chargepoint.GridType, int, time.Time) bool); ok {
		r0 = rf(gridType, phases, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetLifetimeEnergy provides a mock function with given fields: energy, timestamp
func (_m *Cache) SetLifetimeEnergy(energy float64, timestamp time.Time) bool {
	ret := _m.Called(energy, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetLifetimeEnergy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(energy, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetMaxCurrent provides a mock function with given fields: current, timestamp
func (_m *Cache) SetMaxCurrent(current int64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetMaxCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetOfferedCurrent provides a mock function with given fields: current, timestamp
func (_m *Cache) SetOfferedCurrent(current int64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetOfferedCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetOutputPhaseType provides a mock function with given fields: mode, timestamp
func (_m *Cache) SetOutputPhaseType(mode chargepoint.PhaseMode, timestamp time.Time) bool {
	ret := _m.Called(mode, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetOutputPhaseType")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(chargepoint.PhaseMode, time.Time) bool); ok {
		r0 = rf(mode, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetPhase1Current provides a mock function with given fields: current, timestamp
func (_m *Cache) SetPhase1Current(current float64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetPhase1Current")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetPhase2Current provides a mock function with given fields: current, timestamp
func (_m *Cache) SetPhase2Current(current float64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetPhase2Current")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetPhase3Current provides a mock function with given fields: current, timestamp
func (_m *Cache) SetPhase3Current(current float64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetPhase3Current")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetPhaseMode provides a mock function with given fields: mode, timestamp
func (_m *Cache) SetPhaseMode(mode int, timestamp time.Time) bool {
	ret := _m.Called(mode, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetPhaseMode")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, time.Time) bool); ok {
		r0 = rf(mode, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetRequestedOfferedCurrent provides a mock function with given fields: current, timestamp
func (_m *Cache) SetRequestedOfferedCurrent(current int64, timestamp time.Time) bool {
	ret := _m.Called(current, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetRequestedOfferedCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, time.Time) bool); ok {
		r0 = rf(current, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetTotalPower provides a mock function with given fields: power, timestamp
func (_m *Cache) SetTotalPower(power float64, timestamp time.Time) bool {
	ret := _m.Called(power, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for SetTotalPower")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(float64, time.Time) bool); ok {
		r0 = rf(power, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// TotalPower provides a mock function with no fields
func (_m *Cache) TotalPower() (float64, time.Time) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalPower")
	}

	var r0 float64
	var r1 time.Time
	if rf, ok := ret.Get(0).(func() (float64, time.Time)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// WaitForMaxCurrent provides a mock function with given fields: current, duration
func (_m *Cache) WaitForMaxCurrent(current int64, duration time.Duration) bool {
	ret := _m.Called(current, duration)

	if len(ret) == 0 {
		panic("no return value specified for WaitForMaxCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, time.Duration) bool); ok {
		r0 = rf(current, duration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// WaitForOfferedCurrent provides a mock function with given fields: current, duration
func (_m *Cache) WaitForOfferedCurrent(current int64, duration time.Duration) bool {
	ret := _m.Called(current, duration)

	if len(ret) == 0 {
		panic("no return value specified for WaitForOfferedCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int64, time.Duration) bool); ok {
		r0 = rf(current, duration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
