// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedapi

import (
	model "github.com/futurehomeno/edge-easee-adapter/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// ChargerConfig provides a mock function with given fields: chargerID
func (_m *Client) ChargerConfig(chargerID string) (*model.ChargerConfig, error) {
	ret := _m.Called(chargerID)

	if len(ret) == 0 {
		panic("no return value specified for ChargerConfig")
	}

	var r0 *model.ChargerConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ChargerConfig, error)); ok {
		return rf(chargerID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ChargerConfig); ok {
		r0 = rf(chargerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChargerConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chargerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargerDetails provides a mock function with given fields: chargerID
func (_m *Client) ChargerDetails(chargerID string) (model.ChargerDetails, error) {
	ret := _m.Called(chargerID)

	if len(ret) == 0 {
		panic("no return value specified for ChargerDetails")
	}

	var r0 model.ChargerDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.ChargerDetails, error)); ok {
		return rf(chargerID)
	}
	if rf, ok := ret.Get(0).(func(string) model.ChargerDetails); ok {
		r0 = rf(chargerID)
	} else {
		r0 = ret.Get(0).(model.ChargerDetails)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chargerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargerSiteInfo provides a mock function with given fields: chargerID
func (_m *Client) ChargerSiteInfo(chargerID string) (*model.ChargerSiteInfo, error) {
	ret := _m.Called(chargerID)

	if len(ret) == 0 {
		panic("no return value specified for ChargerSiteInfo")
	}

	var r0 *model.ChargerSiteInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ChargerSiteInfo, error)); ok {
		return rf(chargerID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ChargerSiteInfo); ok {
		r0 = rf(chargerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChargerSiteInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chargerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Chargers provides a mock function with no fields
func (_m *Client) Chargers() ([]model.Charger, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chargers")
	}

	var r0 []model.Charger
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Charger, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Charger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Charger)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with no fields
func (_m *Client) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetCableAlwaysLocked provides a mock function with given fields: chargerID, locked
func (_m *Client) SetCableAlwaysLocked(chargerID string, locked bool) error {
	ret := _m.Called(chargerID, locked)

	if len(ret) == 0 {
		panic("no return value specified for SetCableAlwaysLocked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(chargerID, locked)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopCharging provides a mock function with given fields: chargerID
func (_m *Client) StopCharging(chargerID string) error {
	ret := _m.Called(chargerID)

	if len(ret) == 0 {
		panic("no return value specified for StopCharging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(chargerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDynamicCurrent provides a mock function with given fields: chargerID, current
func (_m *Client) UpdateDynamicCurrent(chargerID string, current float64) error {
	ret := _m.Called(chargerID, current)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDynamicCurrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(chargerID, current)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMaxCurrent provides a mock function with given fields: chargerID, current
func (_m *Client) UpdateMaxCurrent(chargerID string, current float64) error {
	ret := _m.Called(chargerID, current)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMaxCurrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(chargerID, current)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
