#!/bin/sh
set -e

case "$1" in
	remove|purge)
		echo "Remove logs"
		rm -rf /var/log/thingsplex/easee || true
		echo "Remove config files"
		rm -rf /opt/thingsplex/easee || true
	;;

	bootstrap)
	;;

	upgrade|abort-upgrade|abort-install|failed-upgrade|disappear)
	;;

	*)
		echo "postrm called with an unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0