#!/bin/sh
set -e

case "$1" in
	upgrade)
		echo "Pause service if running"
		systemctl stop easee.service > /dev/null 2>&1 || true
	;;

	install|abort-upgrade)
	;;

	*)
		echo "preinst called with an unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
