// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/futurehomeno/edge-easee-adapter/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// HandleObservation provides a mock function with given fields: observation
func (_m *Handler) HandleObservation(observation model.Observation) error {
	ret := _m.Called(observation)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Observation) error); ok {
		r0 = rf(observation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsOnline provides a mock function with given fields:
func (_m *Handler) IsOnline() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
