// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	db "github.com/futurehomeno/edge-easee-adapter/internal/db"
	mock "github.com/stretchr/testify/mock"

	model "github.com/futurehomeno/edge-easee-adapter/internal/model"
)

// SessionStorage is an autogenerated mock type for the SessionStorage type
type SessionStorage struct {
	mock.Mock
}

// GetLastChargingSessionsByChargerID provides a mock function with given fields: chargerID, sessionNumber
func (_m *SessionStorage) GetLastChargingSessionsByChargerID(chargerID string, sessionNumber uint) (db.ChargingSessions, error) {
	ret := _m.Called(chargerID, sessionNumber)

	var r0 db.ChargingSessions
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint) (db.ChargingSessions, error)); ok {
		return rf(chargerID, sessionNumber)
	}
	if rf, ok := ret.Get(0).(func(string, uint) db.ChargingSessions); ok {
		r0 = rf(chargerID, sessionNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.ChargingSessions)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(chargerID, sessionNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterStartSession provides a mock function with given fields: chargerID, session
func (_m *SessionStorage) RegisterStartSession(chargerID string, session model.StartChargingSession) error {
	ret := _m.Called(chargerID, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.StartChargingSession) error); ok {
		r0 = rf(chargerID, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterStopSession provides a mock function with given fields: chargerID, session
func (_m *SessionStorage) RegisterStopSession(chargerID string, session model.StopChargingSession) error {
	ret := _m.Called(chargerID, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.StopChargingSession) error); ok {
		r0 = rf(chargerID, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *SessionStorage) Reset() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *SessionStorage) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *SessionStorage) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionStorage creates a new instance of SessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStorage {
	mock := &SessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
