// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	cache "github.com/futurehomeno/edge-easee-adapter/internal/cache"

	mock "github.com/stretchr/testify/mock"

	numericmeter "github.com/futurehomeno/cliffhanger/adapter/service/numericmeter"
)

// specFunc is an autogenerated mock type for the specFunc type
type specFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: report, c
func (_m *specFunc) Execute(report numericmeter.ValuesReport, c cache.Cache) {
	_m.Called(report, c)
}

// newSpecFunc creates a new instance of specFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSpecFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *specFunc {
	mock := &specFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
