name: test

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: fh-ubuntu-22.04
    container:
      image: docker:dind
    steps:
      - name: Test the service
        uses: futurehomeno/github-actions/test@main
        with:
          secrets: ${{ toJSON(secrets) }}
          branch: ${{ github.ref }}

