name: test

on:
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: 'src/go.sum'
      - name: Run tests
        shell: bash
        run: make test
      - name: Publish Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: test_coverage.out
          fail-on-error: false
